services:
  mssql:
    container_name: mssql
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    restart: unless-stopped
    ports:
      - "1433:1433"
  trainingapp:
    container_name: trainingapp
    environment:
      - ASPNETCORE_ENVIRONMENT=
      - ASPNETCORE_HTTPS_PORTS=$HTTPS_APP_PORTS
      - ASPNETCORE_HTTP_PORTS=$HTTP_APP_PORTS
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=$HTTPS_CREDENTIAL"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ConnectionStrings:ApplicationDbContext=Server=mssql,1433;Database=ASPNETCoreMVCTrainingDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True;"
    depends_on:
      - mssql
    ports:
      - "$HTTP_APP_PORTS:$HTTP_APP_PORTS"
      - "$HTTPS_APP_PORTS:$HTTPS_APP_PORTS"
    volumes:
      - ./https/:/https/
networks:
    aspcore-network:
        driver: bridge